### ISSUE TITLE
code for Fourier domain loss compuation

### ISSUE THREAD

**Issue by zhuhanqing** [Westlake-AI/A2MIM#3]
hello, I wanna ask where I can find the codes to compute the Fourier domain loss. thank you so much for your help.

**Comment by Lupin1998** [comment]
Hi, @zhuhanqing. Thanks for your interest in our work, and sorry for the late reply. Please note that the loss functions of A2MIM are implemented in [mim_head.py](https://github.com/Westlake-AI/openmixup/blob/main/openmixup/models/heads/mim_head.py#L161), where the FFT loss (FocalFrequencyLoss) is implemented in [focal_loss.py](https://github.com/Westlake-AI/openmixup/blob/main/openmixup/models/losses/focal_loss.py#L468).

**Comment by Lupin1998** [comment]
Thanks again for your question. If there are no more problems, I will close this issue.
