### ISSUE TITLE
A2MIM ViT-Base ImageNet pretrain cannot be found

### ISSUE THREAD

**Issue by SeongjuLee** [Westlake-AI/A2MIM#5]
Thanks for sharing your valuable work!

I tried to download A2MIM ViT-Base ImageNet pretrain weight, however the url cannot not found as follows.

Would you check the download url?

https://github.com/Westlake-AI/A2MIM/releases/download/a2mim-in1k-weights/full_a2mim_vit_base_l0_res_fft01_sz224_4xb128_accu4_step_fp16_ep800.pth

![image](https://github.com/user-attachments/assets/6faf4fc9-a891-4113-9177-7d14b4493a47)

**Comment by Lupin1998** [comment]
Hi, @SeongjuLee. Thanks for your attention and pointing out the bug. You can download the release models from [a2mim-in1k-weights](https://github.com/Westlake-AI/A2MIM/releases/tag/a2mim-in1k-weights), where the ViT-B checkpoint of A2MIM is available. Feel free to comment if new issues occur.

**Comment by SeongjuLee** [comment]
Thanks for noticing the another download link. There's no problem in download now.
